const images = {
  'Flat Bench Press': require('../../assets/exercises/flat-bench-press.jpg'),
  'Incline Bench Press': require('../../assets/exercises/incline-bench-press.png'),
  'Decline Bench Press': require('../../assets/exercises/decline-bench-press.png'),
  'Machine Chest Press': require('../../assets/exercises/machine-chest-press.png'),
  'Pec Fly': require('../../assets/exercises/pec-fly.png'),
  'Cable Crossover': require('../../assets/exercises/cable-crossover.png'),
  'Push-Up': require('../../assets/exercises/push-up.png'),
  'Chest Dip': require('../../assets/exercises/chest-dips.png'),
  'Low Cable Fly': require('../../assets/exercises/low-cabel-fly.png'),
  'High Cable Fly': require('../../assets/exercises/high-cable-fly.png'),
  'Lat Pulldown': require('../../assets/exercises/latpull-down.png'),
  'Seated Cable Row': require('../../assets/exercises/seated-cable-row.png'),
  'Wide Row': require('../../assets/exercises/wide-back-row.png'),
  'Deadlift': require('../../assets/exercises/deadlift.png'),
  'Barbell Row': require('../../assets/exercises/barbell-row.png'),
  'T-Bar Row': require('../../assets/exercises/t-bar-row.png'),
  'Pull-Up': require('../../assets/exercises/pull-up.png'),
  'Single Arm Dumbbell Row': require('../../assets/exercises/single-arm-dumbell-row.png'),
  'Lats Pullover': require('../../assets/exercises/latpull-over.png'),
  'Barbell Curl': require('../../assets/exercises/biceps-barbellcurl.png'),
  'Dumbbell Curl': require('../../assets/exercises/dumbell-curl.png'),
  'Hammer Curl': require('../../assets/exercises/hammer-curl.png'),
  'Preacher Curl': require('../../assets/exercises/pecher-curl.png'),
  'Cable Curl': require('../../assets/exercises/cable-curl.png'),
  'Incline Dumbbell Curl': require('../../assets/exercises/incline-dumbell-curl.png'),
  'Spider Curl': require('../../assets/exercises/spider-curl.png'),
  'Tricep Extension': require('../../assets/exercises/triceps-pushdown.png'),
  'Skull Crusher': require('../../assets/exercises/skull-crusher.png'),
  'Overhead Tricep Extension': require('../../assets/exercises/overhead-tricep.png'),
  'Single tricep Pushdown': require('../../assets/exercises/single-tricep-pushdown.png'),
  'Wrist Curl': require('../../assets/exercises/wrist-curl.png'),
  'Reverse Wrist Curl': require('../../assets/exercises/reverse-wrist-curl.png'),
  'Reverse Curl': require('../../assets/exercises/reverse-curl.png'),
  'Front Raise': require('../../assets/exercises/front-raises.png'),
  'Overhead Press': require('../../assets/exercises/overhead-press.png'),
  'Machine Shoulder Press': require('../../assets/exercises/machine-overhead-press.png'),
  'Lateral Raises': require('../../assets/exercises/lateral-raises-dumbell.png'),
  'Cable Lateral Raises': require('../../assets/exercises/lateral-raises-cable.png'),
  'Upright Row': require('../../assets/exercises/upright-.png'),
  'Rear Delt Fly': require('../../assets/exercises/rear-delt-fly.png'),
  'Reverse Pec Deck': require('../../assets/exercises/reverse-pec-deck.png'),
  'Face Pull': require('../../assets/exercises/face-pull.png'),
  'Shrugs': require('../../assets/exercises/shrugs.png'),
  'Leg Press': require('../../assets/exercises/leg-press.png'),
  'Squat': require('../../assets/exercises/squat.png'),
  'Romanian Deadlift': require('../../assets/exercises/rdl.png'),
  'Hamstring Curl': require('../../assets/exercises/seated-ham-curl.png'),
  'Pendulum Squat': require('../../assets/exercises/pendulum-squat.png'),
  'Bulgarian Split Squat': require('../../assets/exercises/bss.png'),
  'Leg Extension': require('../../assets/exercises/leg-extention.png'),
  'Calf Raise': require('../../assets/exercises/calf-rasises.png'),
  'Hip Thrust': require('../../assets/exercises/hip-thrust.png'),
  'Hack Squat': require('../../assets/exercises/hack-squat.png'),
  'Walking Lunges': require('../../assets/exercises/walking-lunges.png'),
  'Glute Kickback': require('../../assets/exercises/glutes-kickback.png'),
  'Plank': require('../../assets/exercises/plank.png'),
  'Bench Crunch': require('../../assets/exercises/decline-situp.png'),
  'Hanging Leg Raise': require('../../assets/exercises/leg-raises.png'),
  'Cable Crunch': require('../../assets/exercises/cable-crunch.png'),
  'Wood Chop': require('../../assets/exercises/wood-chopper.png'),
}

export function getExerciseImage(name) {
  return images[name] || null
}
